### ISSUE TITLE
onCompleted not called after onNext

### ISSUE THREAD

**Issue by crabfang** [square/sqlbrite#127]
after QueryObservable created from BriteDatabase.createQuery,
I subscribe this QueryObservable by function subscribe(Observer),
but the method Observer.onCompleted not work after Observer.onNext

**Comment by artem-zinnatullin** [comment]
Because `createQuery()` creates endless `Observable`, it watches changes in the database and notifies you with new result each time related change (tables from query changed)  happens.

You can limit number of emissions of the `Observable` with [filtering operators](http://reactivex.io/documentation/operators.html) like `take(1)`, etc.

**Comment by crabfang** [comment]
I see, thank you
