### ISSUE TITLE
Provide a mechanism and/or pattern for easy pagination

### ISSUE THREAD

**Issue by JakeWharton** [square/sqlbrite#15]
Update the sample to demonstrate with a list containing a few thousand items.

**Comment by rafaelekol** [comment]
Any progress in pagination?
Can I use pagination with current sqlbrite?

**Comment by artem-zinnatullin** [comment]
@rafaelekol `SqlBrite` allows you to use raw `SQL` -> you can use `LIMIT limit_value OFFSET offset_value` feature of `SELECT` in `SQLite`.

Or you want to use pagination via `Observable` emission: for example `emission0(LIMIT 100 OFFSET 0)`, `emission1(LIMIT 100 OFFSET 100)`, `emission2(LIMIT 100 OFFSET 200)`, etc?

**Comment by rafaelekol** [comment]
OK noted,
thanks Artem

**Comment by rafaelekol** [comment]
We have an endless scroll list in our app. Can we use SQLBrite for such scrollList?

**Comment by adelnizamutdinov** [comment]
@artem-zinnatullin have you used that 'emission' pattern for backing an `Adapter`?
did you have any problems with multiple `Subscription`s + multiple simultaneously opened `Cursor`s?

**Comment by artem-zinnatullin** [comment]
@adelnizamutdinov no, I don't see problems with multiple Subscriptions and multiple simultaneously opened Cursors.

Notice: I don't use SqlBrite, so I can make some mistakes.

I see two ways of implementing endless scroll list with RxJava and SqlBrite.

**First variant**: Reactive Pull, but SqlBrite actually not very helpful here, you can use plain `SQLiteDatabase.query()` or `rawQuery()` for that. 

```java
// pseudo code
Observable.create(subscriber -> {
  int offset = 0;
  Cursor cursor;
  
  do {
    cursor = sqlBrite
      .createQuery("SELECT * FROM tweets LIMIT 100 OFFSET ?", offset)
      .map(query -> query.run())
      .toBlocking(); 
      // You can use flatMap and call subscriber.onNext(query.run()) from it
      // But you should use serial Scheduler to guarantee order of emission.
      // To simplify the solution, I'll use imperative way instead of functional.
    
    offset += cursor.getCount();

    subscriber.onNext(cursor);
  } while (cursor.getCount > 0);

  subscriber.onCompleted();
})
.subscribeOn(io())
.observeOn(mainThread())
.subscribe(new Subscriber() { // yes, you need to use Subscriber.
  @Override public void onStart() {
    request(1); // Reactive Pull: Requesting only one item.
  }

  @Override public void onNext(Cursor cursor) {
    adapter.addCursor(cursor);
    // next call to request(1) should happen when list is near to the end
  } 
});
```

But:
* You can not subscribe to changes of tables directly in the paginated query with this solution, because notifications can blow order and content of emissions , so you'll have to monitor it externally and re-execute this Observable.
* You should keep in mind that this implementation won't make your Observable lazy, it'll execute all queries when Subscriber will subscribe to it and Subscriber's Provider would store all emissions in Queue and pass it to you as you request, so it won't be as much faster and resource cheaper than one request without pagination.

**Second variant**: Pagination without Reactive Pull

```java
// pseudo code

// Fragment/Activity/Presenter
class SomeUiController {
  
  void onNearToEndOfList() {
    loadMoreData(list.getItemsCount())
      .observeOn(mainThread())
      .subscribe(cursor -> adapter.addCursor(cursor));
  }

  @NonNull
  public Observable<Cursor> loadMoreData(int offset) {
    return sqlBrite
      .createQuery("SELECT * FROM tweets LIMIT 100 OFFSET ?", offset)
      .map(query -> query.run())
      .subscribeOn(Schedulers.io());
  }
}
```

And Adapter implementation:
```java
// pseudo code
class EndlessAdapter extends RecyclerView.Adapter {
  
  @NonNull
  private final List<Cursor> cursors = new ArrayList<>();

  public void addCursor(@NonNull Cursor cursor) {
    cursors.add(cursor);
    notifyDataSetChanged();
  }

  public void removeCursor(@NonNull Cursor cursor) {
    cursors.remove(cursor);
  }

  @Override
  public int getItemsCount() {
    int totalCount = 0;

    for (int i = 0, count = cursors.size(); i < count; i++) {
      totalCount += cursors.get(i).size();    
    }

    return totalCount;
  }

  // I am not sure that implementation is 100% correct, please add tests.
  @NonNull
  Cursor getCursorByItemPosition(int itemPosition) {
    int offset = 0;

    for (int i = 0, count = cursors.size(); i < count; i++) {
      final Cursor cursor = cursors.get(i);

      if (itemPosition >= offset && itemPosition < offset + cursor.getCount()) {
        cursor.move(offset - itemPosition);
        return cursor;
      }

      offset += cursor.getCount();
    }

    throw new IllegalArgumentException("Can not find cursor for requested item position: " + itemPosition);
  }

  public void onBindViewHolder(@NonNull ViewHolder viewHolder, int position) {
    final Cursor cursor = getCursorByItemPosition(position);

    // display the data from cursor. 
  }
}
```

Notice: you MUST update cursors in the adapter if data in the db was changed, otherwise pagination can produce problems with displaying one item several times in case when data was added or not displaying item in case when date was removed:

**Item was added:**
Time0: `Data in db: (item0, item1, item2, item3, ..., item100)`

Ui:
Time1: `Limit 4, Offset 0, Data in list (item0, item1, item2, item3)`
Time2: `Data update (item2' was added between item2 and item3)`
Time3: `List scrolled down, loading more…`
Time4: `Limit 4, Offset 4, Data in list (item0, item1, item2, item3, item3, item4, item5, item6)`
// item2' won't be displayed!
// item3 will be displayed twice!

**Item was removed:**

Time0: `Data in db: (item0, item1, item2, item3, ..., item100)`

Ui:
Time1: `Limit 4, Offset 0, Data in list (item0, item1, item2, item3)`
Time2: `Data update (data3 was removed)`
Time3: `List scrolled down, loading more…`
Time4: `Limit 4, Offset 4, Data in list (item0, item1, item2, item3, item5, item6, item7, item8)`
// item3 won't be removed from the list!
// item4 won't be displayed!


As you can see, I am not a big fan of pagination -> it requires too much code and can produce hard-debuggable bugs.

When data set is really huge (for example several thousands of items), you can make one request to load all ids of the items and then load each item's data synchronously or asynchronously in the adapter's bindViewHolder()/getView(), but yes, sometimes pagination is really required.

I don't see how to integrate observing changes in tables with pagination in one Observable.

**Comment by ranadeep47** [comment]
Any update on this please ?

**Comment by sharathp** [comment]
+1, thanks

**Comment by sharathp** [comment]
Isn't a simple Cursor sufficient for this?, i.e., a SQLite based cursor using something like 'SELECT * FROM <items> ORDER BY <timestamp> DESC"? and then use something similar to a CursorAdapter which will be updated on  notifications to the subscriber?

since cursor doesn't retrieve all the data into memory at once, this would scale well for thousands of items, no?

**Comment by aashrairavooru** [comment]
this is not SQLBrite specific but i think this should do https://gist.github.com/mttkay/24881a0ce986f6ec4b4d

**Comment by JakeWharton** [comment]
Google is releasing a thing for this. No action to take.
