### ISSUE TITLE
Question using rxjava2

### ISSUE THREAD

**Issue by joeyslalom** [square/sqlbrite#162]
I'm attempting to use Sqlbrite in an app using RxJava2.  I can use the interop library to convert the V1 observable to a V2 observable, but I also realized the wrapDatabaseHelper() function takes a V1 scheduler.

Is it appropriate to use V1 Schedulers.io()?  Is there a more performant/correct answer while we're in-between V1 & V2?  All I know is my app doesn't blow up (yet) :)

**Comment by JakeWharton** [comment]
Yes, that's fine for now. `Schedulers.io()` is just a thread pool in both versions so they'll have the same effect. You could also propose to the interop library to provide converters for `Schedulers` since it wouldn't be that hard.

The SQL Brite sample depends on RxBinding so once it ships an RxJava 2 version (in the next week or three) we'll port this library over and make a 2.x release.

**Comment by joeyslalom** [comment]
Thanks!
