### ISSUE TITLE
Lint Warning when using mapToOne

### ISSUE THREAD

**Issue by shaishavgandhi05** [square/sqlbrite#244]
There can be a lint check which tries to parse the SQL query and warn if there is not `LIMIT 1` in that query. 
This caused a problem for me where even though we had a `mapToOne`, a duplicate value got in somehow which caused the crash. It would be useful to have this Lint warning. 

Happy to send a PR!

**Comment by shaishavgandhi05** [comment]
Hey @JakeWharton do you see a use case for this? I think it's a nice-to-have.

**Comment by JakeWharton** [comment]
We're in the process of making this library obsolete with SQL Delight 1.0 which integrates the update tracking that this library performs. As a result, I don't think we're going to spend any time adding functionality here–especially in the form of a lint check since it's unlikely we'll make another release. Thankfully, because this is lint, you can still write such a check and apply it to your codebase in the mean time.
