### ISSUE TITLE
Order of operators mapToOne and take(1) - clarification on #69, #77

### ISSUE THREAD

**Issue by cxzhang2** [square/sqlbrite#83]
Can someone explain to me the difference between the following?

`take(1).lift(Query.mapToOne())`

vs

`mapToOne().take(1)`

Or to put it another way, how does PR #77 address the "empty row" scenario raised in issue #69?  My RxJava knowledge is lacking so it seems to me that the two approaches are identical except for the reversed method invocations.

**Comment by JakeWharton** [comment]
They are the same. The issue was that you cannot do `take(1).mapToOne(..)` because calling `take(1)` returns `Observable` and `mapToOne()` is only available on `QueryObservable` (which is returned from `query`).

**Comment by JakeWharton** [comment]
Oh, and the problem was when the query returns zero results. `mapToOne().take(1)` would hang forever in this instance because it does not emit when there is no results. Thus it never completes

It is solved by `take(1).lift(mapToOne())` because `take(1)` calls onCompleted after the first trigger, regardless of how many rows are in the query result. So when `mapToOne()` never calls onNext, the onCompleted immediately follows it.
